### ISSUE TITLE
May you helpe me to   log in android, thanks

### ISSUE THREAD

**Issue by onunix** [TooTallNate/Java-WebSocket#1022]
In android ,I get a error :
2020-05-14 14:02:45.336 22211-22211/? W/System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2020-05-14 14:02:45.336 22211-22211/? W/System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
2020-05-14 14:02:45.336 22211-22211/? W/System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

then I add a dependence:
implementation files('lib\\slf4j-android-1.6.1-RC1.jar')

It reported Duplicate class org.slf4j.helpers.MessageFormatter found in modules slf4j-android-1.6.1-RC1.jar (slf4j-android-1.6.1-RC1.jar) and slf4j-api-1.7.25.jar (org.slf4j:slf4j-api:1.7.25)

how can I see the log ?
thanks!

**Comment by PhilipRoman** [comment]
Can you share your build configuration or post a link to your repository?

**Comment by onunix** [comment]
here is another project  by another author ,  https://github.com/yangxch/WebSocketClient  when I run ,it also:  Failed to load class "org.slf4j.impl.StaticLoggerBinder". the error comes from LogFactory.java:
Set<URL> staticLoggerBinderPathSet = null;
            // skip check under android, see also
            // http://jira.qos.ch/browse/SLF4J-328
            if (!isAndroid()) {
                staticLoggerBinderPathSet = findPossibleStaticLoggerBinderPathSet();
                reportMultipleBindingAmbiguity(staticLoggerBinderPathSet);
            }
            // the next line does the binding
            StaticLoggerBinder.getSingleton();
            INITIALIZATION_STATE = SUCCESSFUL_INITIALIZATION;
            reportActualBinding(staticLoggerBinderPathSet);
            fixSubstituteLoggers();
            replayEvents();
            // release all resources in SUBST_FACTORY
            SUBST_FACTORY.clear();

**Comment by PhilipRoman** [comment]
1. The project you linked to doesn't declare a dependency on any SLF4J backend. This causes the warning `Failed to load class "org.slf4j.impl.StaticLoggerBinder"`. To add a backend, put something like this in build.gradle:
```
implementation group: 'org.slf4j', name: 'slf4j-simple', version: '1.7.25'
```

2. The error `Duplicate class org.slf4j.helpers.MessageFormatter` happens because you're using both `slf4j-api` and `slf4j-android` jars. If I understand correctly, `slf4j-android` already contains `slf4j-api` classes (see http://www.slf4j.org/android/), so you should replace `slf4j-android` with another backend like `slf4j-simple`.

**Comment by PhilipRoman** [comment]
Has this issue been solved for you?
