### ISSUE TITLE
How to send WebSocket's in path<ws://url:port/path> ? 

### ISSUE THREAD

**Issue by leesangboo** [TooTallNate/Java-WebSocket#103]
How to send WebSocket's in pathws://url:port/path ? 

if ChatServer Client URL == ws://localhost:8887/chat

**Comment by sabhiram** [comment]
@Davidiusdadi - I think what @leesangboo, and what I wish to answer is the following:

How do I connect to a subpath if my websocket server only accepts connections to:
`ws://<ip>:<port>/<path>`

The question is not asking how one might get a path from a given open connection, but rather how one would connect to a subpath in a websocket server.

Perhaps this can be re-opened?

**Comment by lvivtotoro** [comment]
Yes, this would be pretty useful

**Comment by marci4** [comment]
Hello @lvivtotoro,

I currently don't understand what exactly would be useful. Could you elaborate more?

Greetings
marci4

**Comment by marci4** [comment]
No feedback on this issue for a month.

Reclosing the issue then!
Greetings
marci4

**Comment by gitEmporer** [comment]
Hi, 

I have a similar requirement to specify a path, when sparting a WebSocketServer.

A sample how this works in other websocket implementations can be found here:
https://www.oracle.com/technetwork/articles/java/jsr356-1937161.html
The sample on the page uses a context (path): `mycontextroot `and an endpoint: `hello`.
Sample URL is :  `ws://localhost:8080/mycontextroot/hello`

For your framework I only need a way to configure the path.

Regards

**Comment by PhilipRoman** [comment]
This library currently does not provide path/endpoint resolution. Instead of starting 2 different servers `ws://localhost:1234/foo` and `ws://localhost:1234/bar`, you start a single server on `ws://localhost:1234` and within the `onOpen(...)` method you can check the requested endpoint using `handshake.getResourceDescriptor()` which returns a string, like `"/foo"` or `"/foo/bar"` and then implement further logic in your own code.

While this library probably won't implement full endpoint resolution, we could potentially offer basic support for registering callbacks to only be invoked for sockets whose handshake endpoint matches a certain path.
