### ISSUE TITLE
Issue with Draft.java in latest Java on linux

### ISSUE THREAD

**Issue by newsbubbles** [TooTallNate/Java-WebSocket#1124]
I'm using the latest java available for Ubuntu 20.0.4 LTS but I installed java from the official site.

### java -version
`java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)
`
### Error
So when trying to run on my new laptop I got the error:

`Exception in thread "WebSocketConnectReadThread-30" Exception in thread "WebSocketConnectReadThread-29" java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
	at org.java_websocket.drafts.Draft.createHandshake(Draft.java:265)
	at org.java_websocket.drafts.Draft.createHandshake(Draft.java:226)
	at org.java_websocket.WebSocketImpl.startHandshake(WebSocketImpl.java:690)
	at org.java_websocket.client.WebSocketClient.sendHandshake(WebSocketClient.java:485)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:410)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
	at org.java_websocket.drafts.Draft.createHandshake(Draft.java:265)
	at org.java_websocket.drafts.Draft.createHandshake(Draft.java:226)
	at org.java_websocket.WebSocketImpl.startHandshake(WebSocketImpl.java:690)
	at org.java_websocket.client.WebSocketClient.sendHandshake(WebSocketClient.java:485)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:410)
	at java.lang.Thread.run(Thread.java:748)
`
### My Findings
I checked the code in your repository for Draft.java and I know I am using version 1.3.9 (2018-08-05)
In your current code, the same method; ByteBuffer.flip() is still used on line 294 so I'm assuming that this means your library will not work in OpenJDK Java 11 without some sort of accounting for this.

I found this on stackoverflow: https://stackoverflow.com/questions/61267495/exception-in-thread-main-java-lang-nosuchmethoderror-java-nio-bytebuffer-flip

The other thing that is weird is that it works in Eclipse that I have installed on the same system when I run it.  So this quite possibly is my own issue of some sort of java versioning or whatever.  I will fix stuff on my side because I need my project to continue, but I wanted to log this with you guys just in case there is anything you need to do.  Basically when I run my software from a compiled bundled jar from CLI, I get this error, but in the latest version of eclipse I do not.  I am pretty sure I only have one version of java installed, so I'm not completely sure what's going on.  I will check on my own.

Thanks for a great lib, keep up the good work!

**Comment by PhilipRoman** [comment]
If you're using the jar that comes from maven central, it seems to be compiled with Java 1.7, so it should be compatible with 1.8 (but not 1.9+). For some reason, I've never encountered this error when using the library with latest jdk. I will verify this and if that happens, we should probably use the fix provided in the answer to maintain compatibility - `((Buffer) b).flip();`.

Of course, for emergency situations there is always the option of building the library yourself with whatever JDK you use.

**Comment by PhilipRoman** [comment]
If I understand correctly, the maven central jar is currently built with bytecode version 1.7, but uses the `ByteBuffer` methods (instead of the old `Buffer` methods) introduced in JDK 9. If that is the case, we should build the jar with an actual 1.7 or 1.8 JDK or introduce an explicit cast to `Buffer` when using these new methods to maintain compatibility.

This seems to be the list of overridden methods:
* position​(int newPosition)
* limit​(int newLimit)
* flip​()
* clear​()
* mark​()
* reset​()
* rewind​()

**Comment by marci4** [comment]
@PhilipRoman I always build the jar with 1.8 JDK, otherwise I would no longer be able to build it against 1.7

Best regards,
Marcel

**Comment by PhilipRoman** [comment]
@marci4
You're right, the jars are fine and don't contain any incompatible calls. No action is needed.

@newsbubbles
How are you downloading the library - are you using a dependency management tool or compiling it yourself? The error you are getting happens when you compile the library with JDK 9 or above and running it from JDK 8 or below.

My best guess is that the jar was compiled using `javac --target 8 ...`, but the JDK itself was newer, so it used the incompatible method.

**Comment by marci4** [comment]
@newsbubbles any update?

**Comment by newsbubbles** [comment]
I fixed it by upgrading default java version on Ubuntu to OpenJDK 14, thanks for the input guys!
