### ISSUE TITLE
Fragmentation

### ISSUE THREAD

**Issue by whateverUsernameAvailable** [TooTallNate/Java-WebSocket#1268]
Hello, I found this example as your answer to fragmentation question.

https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/FragmentedFramesExample.java

But if I am not mistaken, this only allows to send large message split into pieces, I assume it does not allow to send different message in between the big one as the 
`websocket.sendFragmentedFrame(Opcode.TEXT, longelinebuffer, false);`
does not contain any message UID

I would need to be able to split big messages into smaller pieces so that when I receive request with strict response timeout I can answer it immediately and then continue to send the large message. Is that even possible with websocket protocol and how to achieve it with this library ?

Thank you for your answer, Lukas

**Comment by PhilipRoman** [comment]
What you describe is generally not possible due to how WebSocket protocol works. If you want to multiplex your connection this way, you need to either use multiple connections or implement message splitting at a higher layer as part of your own API instead of relying on the WebSocket built in framing.
