### ISSUE TITLE
Error AndroidRuntime Caused by: java.lang.ClassNotFoundException: org.java_websocket.client.WebSocketClient

### ISSUE THREAD

**Issue by ZFHung** [TooTallNate/Java-WebSocket#1405]
i Export aar to Unity，Unity Report 

Error AndroidRuntime Caused by: java.lang.ClassNotFoundException: org.java_websocket.client.WebSocketClient

how to fix it?

**Comment by PhilipRoman** [comment]
The message just means that Java-WebSocket library was not found. I'm not familiar with AAR but I guess you need some way to include all libraries into it. I see there are some plugins which does this: https://plugins.gradle.org/plugin/com.cpdroid.fat-aar but unfortunately it is outdated. I found multiple questions on stackoverflow but looks like there is no official solution for this, people either use the plugin or copy files manually.

Anyway, I'm closing this issue because it is a general Java question, not related to this library.
