### ISSUE TITLE
AssertionError thrown in connect method of SocketChannelImpl class in Android sdk

### ISSUE THREAD

**Issue by gayatrimali** [TooTallNate/Java-WebSocket#323]
I am using Java-WebSocket 1.3.0 version for establishing websocket connection from android app.
SocketChannel implementation used is from android sdk jar, which calls IoBridge.connect with connect timeout zero and assumes that SocketTimeoutException can't happen for a connect without a timeout. So SocketTimeoutException is catched and AssertionError is thrown instead in IoBridge.connect method.

Following is the stack trace.
java.net.SocketTimeoutException: failed to connect to xyz after 90000ms
    at libcore.io.IoBridge.connectErrno()(IoBridge.java:176)
    at libcore.io.IoBridge.connect()(IoBridge.java:112)
    at libcore.io.IoBridge.connect()(IoBridge.java:100)
    at java.nio.SocketChannelImpl.connect()(SocketChannelImpl.java:177) 

I have seen latest master branch code which does not use SocketChannel interface for establishing connections. Can you please release next stable version of Java-WebSocket ? 
Otherwise please suggest some other way. I am also willing to create pull request to handle AssertionError in WebSocketClient class (which is thrown in case of android integration)

**Comment by BrushfireDigitalServices** [comment]
Thank you for your input, @gayatrimali. Too much has changed in the ecosystem and this code since the 1.3.0 snapshot to avoid doing a new stable release in any case; see the milestone Release 1.4.0. Android has historically been a buggy area for this project, for the above reasons and poor TLS support in the Android libraries <4.1.

If you are interested in helping fix this or any other issue, please do write a pull request. 

@ThreaT and I are administrating this project for the foreseeable future, so you can expect to see responses to your efforts.

Do what you feel confident and inspired to create. However, keep in mind that we are in a push to complete documentation and provide unit test coverage. Therefore, all new code (and the existing methods it modifies) must meet these requirements to be merged.

**Comment by hezhubo** [comment]
Is this bug fixed?

**Comment by marci4** [comment]
Hello @hezhubo

could you please use the latest version 1.3.2 to check if this issue is fixed for you?

Greetings
marci4

**Comment by hezhubo** [comment]
Hello @marci4 
I use the version 1.3.1, but I remove the code

> assert ( socket.isClosed() );

It seem that it's OK now. I need to watch for some time.

**Comment by marci4** [comment]
Hello @hezhubo 

that is not the solution to the problem, just a work around.
_(For tracking: Could be related to #302 )_

Greetings
marci4

**Comment by hezhubo** [comment]
Hello @marci4 
I will be updating my app in the next version. Because this problem is not necessarily appear, so I can only let the user to test.
But assert whether it is necessary?

**Comment by marci4** [comment]
hello @hezhubo 

do you have any update on this issue?

Greetings
marci4

**Comment by hezhubo** [comment]
Hello @marci4 
Now, I use the version 1.3.3. And I also delete the assert code

> assert ( socket.isClosed() );

I do not think it is necessary. Because it is runnable and no crash.

**Comment by marci4** [comment]
No feedback!

If you still have this issue, please open a separate thread!
Greetings
marci4
