### ISSUE TITLE
Using this lib without problems: feedback on wss://

### ISSUE THREAD

**Issue by gesellix** [TooTallNate/Java-WebSocket#325]
Hi, as stated in the readme you're interested if secure websockets are working for us. I can tell that it seems to work well using the current 1.3.0 release in the [docker-client](https://github.com/gesellix/docker-client) project.

Thanks for working on this nice non-bloated library!

**Comment by BrushfireDigitalServices** [comment]
Thank you for your input! It's good to hear that docker-client seems to be running smoothly. I've applied labels and will keep this issue open as a centralized place for further feedback about our wss support.

**Comment by garys-esri** [comment]
Many thanks for this useful library and sample code. I used Java-WebSocket to successfully connect to an [ArcGIS Server stream service](http://server.arcgis.com/en/server/latest/publish-services/windows/stream-services.htm), which is a secure WebSocket. I used the techniques in [SSLClientExample.java](../blob/master/src/main/example/SSLClientExample.java). Since my service uses a certificate signed by my company's CA instead of a well-known CA, I also had to [trust untrusted certificates](http://stackoverflow.com/a/1201102/720773), which is a bad idea in production code but enabled me to make sure the Java-WebSocket library would work with this type of service.

**Comment by blunden** [comment]
@garys-esri It's not just "a bad idea", trusting all certificates should NEVER be done in production code. What you want in this case is probably to pin your company CA certificate in the client. The current example code shows you how to do this (add the certificate into a jks keystore and specify that as the trust store to trust).
