### ISSUE TITLE
What is the maximum client concurrent connections that web socket server can accept?

### ISSUE THREAD

**Issue by iraj-wisilica** [TooTallNate/Java-WebSocket#340]

**Comment by JBearded** [comment]
I also want to know

**Comment by marci4** [comment]
Hello @iraj-wisilica and @JBearded 

I digged a bit into this topic and I think the limiting factor is how many threads you can spawn because each connection is getting its own thread to handle all its calls.
Internally we (normaly) use a HashSet to store all the current connections so that would be the maximum limit, which is close to Integer.MAX_VALUE afaik.

Greetings
marci4

**Comment by Kojesnik** [comment]
Hello @marci4, I faced a connection limit of 3727 connections. This number is static and nothing helps. Also, I have been tested threads on my server, and everything is ok, it can spawn lots of threads. What can be the problem?
