### ISSUE TITLE
Websocket server returning 401; can't handle on client side

### ISSUE THREAD

**Issue by chenfisher** [TooTallNate/Java-WebSocket#390]
I have a websocket server that returns 401 on the http handshake
I can't figure out how to get that information on the websocket client

Two things I can't figure out:
1. Where can I get the http status code returned form the server (401 in this case)
   onClose is called but with irrelevant code (-1) which I saw in your code that it means "never connected"
2. onError is called but for totally different reason. I get onError ssl == null
   why would the client library continue to try to decode the handshake, or something like that, when the socket wasn't upgraded (101)? why not just stop there? The ssl error is irrelevant here and is fired do to the fact that the server did not upgrade the socket

What I did to get the status code from the server was to subclass my own Draft, implement acceptHandshakeAsClient and copyInsance; this gave me access to the handshake response
When I see that the status code is 401 I return NOT_MATCHED
This is the only place I saw I can get the status code, but it makes me do ugly things like saving the status code in a variable to be used by onClose and onError which are then called (but with irrelevant data - code == -1 and error exception is ssl == null)

Thanks

**Comment by felippeduran** [comment]
The pull request #567 fixes the exactly issue mentioned by the item 1.

Regarding the item 2, I had the same issue when trying to handle a status code 503 during the HTTP handshake (mentioned on the pull request).

What seems to be a good solution is to make the `Draft_6455` propagate these status codes to the websocket class and then expose it as a connection failure instead of `CloseFrame.PROTOCOL_ERROR`, even though the [RFC6455](https://tools.ietf.org/html/rfc6455) doesn't mention how to handle these errors (at least I couldn't find it).

Thanks!

**Comment by marci4** [comment]
Hello @felippeduran,
I will be able to test this issue probably in two days.

Regarding the item 2, what do you think of an additional onError call with an exception indicating an invalid http status code?

Greetings
marci4

**Comment by marci4** [comment]
Hello @felippeduran again,

I added a reason for the onClose call, if there was an error with the status code or status line.

Issue should be solved by that.

Greetings
marci4
