### ISSUE TITLE
SSL using legit (non-self signed) certificate.

### ISSUE THREAD

**Issue by vedi0boy** [TooTallNate/Java-WebSocket#415]
I tried to create a server hosted on the same server as my website with https on it. (https://hollowbit.net/vedi0boy/). You can see https works, but when I try using it for websockets, it doesn't. Is there a way to do it or is it simply not implemented yet.

When using applications made with gwt (java converted to javascript) for example, it doesn't allow you to connect to self-signed certificate servers for security reasons. Also, it looks a lot more legit if I don't use them.

Thanks!

**Comment by marci4** [comment]
Hello @vedi0boy,

I should be able to provide an example for you to use a certificate (Let's encrypt) for the server.

Gonna add a documentation.

Greetings
marci4

**Comment by bendem** [comment]
[Here](https://gist.github.com/bendem/7548d3dd2b2869e2d4ef) is the code I used to generate a keystore from a regular certificate; and [here](https://github.com/bendem/IrcSockets/blob/master/src/main/java/be/bendem/irc/ircsockets/ws/Server.java#L46) is an example usage.

The code is pretty old, I ended up not using this project because the code was old and full of weird quircks. But the idea is there.

**Comment by marci4** [comment]
Hello @vedi0boy,

please check out my wiki post with some examples [here](https://github.com/TooTallNate/Java-WebSocket/wiki/Getting-a-SSLContext-from-different-sources).

Greetings
marci4

**Comment by vedi0boy** [comment]
Awesome! I will try it when I get the chance. Does this only work with Let's Encrypt? I use it but I'm just curious for people using other CAs.

**Comment by marci4** [comment]
Hello @ve
