### ISSUE TITLE
Hostname resolving

### ISSUE THREAD

**Issue by rashaverak** [TooTallNate/Java-WebSocket#434]
Hi, it seems that hostname is always resolved to ip address, which cause me problems that server delivers different certificate. Can I force  the lib to not resolve the hostname ?

**Comment by marci4** [comment]
hello @rashaverak,

Let me try to understand your problem:

- You are using one websocket server (wss)
- You wanna listen to example.org and example2.org (and not a different sub domain)
- You have one certificate for each domain
- You have the same business logic for both domains

Your problem is now that you get a certificate error when you try to access the wss with example.org while you used the certificate for example2.org
Is that correct?

Greetings
marci4

**Comment by rashaverak** [comment]
I have 2 different servers. I connect to them using host names. They use different certificates for different host names. In case of my connection the servers use default certificates and not these that I want, like if the host names I set were ignored and they were just resolved to ip address and that was used for the connection. On one it works by accident because the default certificate is the one that I want. It has something to do with the SNI I believe.

**Comment by marci4** [comment]
Ahhh ok, I quess I now understand your problem.

Well I can't really help you with this problem because we use a native Java Socket which just allows us to bind to a specific IP-address. 
Without any managing software above the connection something like SNI is not possible.

I would recommend to you that you use just a different port for your second server (You should have had a bind exception that the address is already in use anyway!)

Hope I was able to help you!
Greetings
marci4

**Comment by rashaverak** [comment]
Found solution, maybe useful for someone

SSLSocket sslSocket = (SSLSocket) sslContext.getSocketFactory().createSocket();
                SNIHostName serverName = new SNIHostName("example.com");
                List<SNIServerName> serverNames = new ArrayList<>(1);
                serverNames.add(serverName);

                SSLParameters params = sslSocket.getSSLParameters();
                params.setServerNames(serverNames);
                sslSocket.setSSLParameters(params);
                setSocket(sslSocket);

Thank you anyway for you time.

**Comment by marci4** [comment]
Thx for your answer, sorry that I did not get your question!

Closing the issue!
Greetings
marci4

**Comment by bionicbrad** [comment]
@rashaverak where/how did you use that code?  Can you give a bit more context?
