### ISSUE TITLE
Improve lost connection detection

### ISSUE THREAD

**Issue by marci4** [TooTallNate/Java-WebSocket#473]
E.g. using this lib on a smartphone, you may lose the connection.

Related issues:
#471 
#180

**Comment by marci4** [comment]
Looking for some input here!

I implemented a check with a timer.
It sends pings in a definied interval (default: 30s)
If there was an error sending this ping, the websocket gets closed
You can deactivate this check setting the interval below 1.

Check out the code [here](https://github.com/marci4/Java-WebSocket-Dev/tree/lostconnection) 

Did I miss something?
Should I add anything?

Greetings
marci4

**Comment by zhoulifu** [comment]
Hello @marci4 
In my opinion, it's not enough to detecting the disconnection just sending ping. 
For example, one client was shut down suddenly, without sending closeframe or closing the connection,  the server could still send message to this disconnected connection without any errors due to the tcp retransmission. Drop all outgoing packages from client side using iptables can simulate this scenario:
```
iptables -A OUTPUT -p tcp --sport {CLIENT_PORT} -j DROP
```
So it's necessary to check whether the corresponding pong was received. But this would bring more pressure to server when there are plenty of clients

**Comment by marci4** [comment]
Ok I added a check for the pong response.

Default check interval is 30 seconds, is this to often?

Could you please check if for you this is working as well?

Greetings
marci4

**Comment by zhoulifu** [comment]
Hey @marci4, i've tested it and it works :+1: 
30s is okay i think since pong arrived within hundreds of milliseconds in general.

**Comment by marci4** [comment]
Hello @zhoulifu,
thx for your feedback.
Gonna leave this issue open and not yet merch any changes. 
Just to give other users time to give feedback as well!

Greetings
marci4

**Comment by marci4** [comment]
Merged changes into master branch.

Closing issue.
Greetings
marci4

**Comment by marci4** [comment]
wiki article https://github.com/TooTallNate/Java-WebSocket/wiki/Lost-connection-detection

**Comment by qhchen2** [comment]
Could you create an example that uses this lost detection connection? Im trying to follow the wiki and My Server that extends WebsocketServer doesn't recognize the method myServer.setConnectionLostTimeout(15). The wiki is pretty short so I'm not exactly sure where I'm going wrong

**Comment by marci4** [comment]
Lost connection is not yet released as a jar. It will come with the version 1.3.4 (no release date planned sorry)

You can also use the master branch which already includes the lost connection detection!

Greetings
marci4

**Comment by qhchen2** [comment]
Thanks for the quick reply, maybe examples on what methods to call in the js client and what methods in the server and to put it all in an example. Even if 1.3.4 was released the wiki is unfortunately so short I would not have understood the example(The same with trying to do wss, had alot of problems trying to make that work. As for me, Im forced to use 1.3.3 for now, so Im trying to implement the ping/pong thing myself. What is not clear for me from the wiki what ping and pong are exactly, strings, objects etc? also some kind of interaction diagram would be handy. So right now im unsure what to send to the client from the server and what method to use. Im guessing I could use websocket.send(String) but maybe thats not ideal because of the overhead.

Greetings,
Q

**Comment by qhchen2** [comment]
Im using a javascript client and am wondering how to check for pings from a server in a regular interval there. Did you use JS also and have found a solution? JS does not appear to have multithreading

**Comment by marci4** [comment]
Hello @qhchen2,

I am gonna extend the wiki a bit more then (Sorry, for me these things are pretty clear ;) )

Let me explain some stuff for you!
A ping is specified by https://tools.ietf.org/html/rfc6455#section-5.5.2 
A pong is specified by https://tools.ietf.org/html/rfc6455#section-5.5.3
If an endpoint recieves a ping frame it must respond with a pong frame. That is the basic idea behind this feature!
If you are using a valid endpoint implementing the spec correctly (what you can assume from modern browsers), you don't have to do anything (most modern browser don't even show ping/pong frames).

Greetings
marci4

**Comment by qhchen2** [comment]
Hey marci, just a quick question on some code I found in AbstractWebSocket class in the master, namely

/**
     * Attribute for the lost connection check interval
     */
    private int connectionLostTimeout = 60;

    /**
     * Get the interval checking for lost connections
     * Default is 60 seconds
     * @return the interval
     */
    public int getConnectionLostTimeout() {
        return connectionLostTimeout;
    }
Is this your code that is not part of 1.3.3, or is it code that has been part of the project for a long time? cause now it seems I can just use these builtin functions and variables to makethe pingpong work.

Greetings,
Q

**Comment by marci4** [comment]
Hello @qhchen2,

the code is part of my connection lost detection!
The master branch is always a representation of the current development status!

Greetings
marci4

**Comment by NitzDKoder** [comment]
@marci4 on Android we are getting **reason: The connection was closed because the other endpoint did not respond with a pong in time. For more information** 

Cleint:

Request is done from android webview level web-socket as client.



say if setConnectionLostTimeout(30secs), Server will auto detect and wait for message from cleint?

Thanks
Nithin
