### ISSUE TITLE
how to set the PING-PONG timeout

### ISSUE THREAD

**Issue by sww0825521xy** [TooTallNate/Java-WebSocket#520]
when the client android device connect to the server android device. If restart the client device, the server device will receive the onClose after 1 minute. How to set the timeout?

**Comment by marci4** [comment]
Hello @sww0825521xy 

If I understand correctly, the android client is not correctly closing the connection to the server due to e.g. lost internet.
Therefore I implemented a lost connection connection (Check [here](https://github.com/TooTallNate/Java-WebSocket/wiki/Lost-connection-detection)).
If you wanna shorten the ping interval, decrease it with 

```java
ChatServer s = new ChatServer( port );
s.setConnectionLostTimeout( <new interval> );
s.start();
```

Greetings
marci4

**Comment by sww0825521xy** [comment]
Hi marci4
I use setConnectionLostTimeout to set timeout for both server and client device. If client lost connection, server will receive the onClose after timeout. But if server lost connection, client will not receive the onClose after timeout.
WebSocketClient.setConnectionLostTimeout(9);

**Comment by marci4** [comment]
Hello @sww0825521xy 

could you please activate the debug printouts with `WebSocketImpl.DEBUG = true;` and post the log here so I can understand what is going wrong!

Greetings
marci4

**Comment by sww0825521xy** [comment]
Hi marci4
I have uploaded the client log and enable the log switch.
[client.txt](https://github.com/TooTallNate/Java-WebSocket/files/1138349/client.txt)
client onOpen : 07-11 05:19:11.679: I/ClientService(9488): onOpen:Web Socket Protocol Handshake
client close log will print :  onClose code:
If the server lost connection, the client will not receive the onClose callback.

**Comment by marci4** [comment]
Hello @sww0825521xy 
that log has close to 5000 lines. That won't help me....

Greetings
marci4

**Comment by sww0825521xy** [comment]
Hello marci4
You can start from line 4606 when the client receive onOpen callback.

**Comment by marci4** [comment]
I am sorry but I do not have time to go through so many unrelevant lines...

**Comment by marci4** [comment]
Hello @sww0825521xy,

finally got enough time to check out these 5k lines of log.

Looks like it could be related to #504. Like some implementations (mostly Android) are not updating the selector and because of that not correctly closing everything down!

Could you maybe try to patch #506 and give me some feedback.

Greetings
marci4

**Comment by sww0825521xy** [comment]
Hello marci4
I will download the master code and test it. Give you feedback ASAP.

**Comment by sww0825521xy** [comment]
Hello marci4
I download the master code with the patch #506 and test on my android devices.
if server lost connection, client now will receive the onClose callback after the timeout.
patch #506 fix the issue.

**Comment by marci4** [comment]
Hello @sww0825521xy,
thx for your feedback.

As I understand you correctly, I can close this topic right?

Greetings
marci4
