### ISSUE TITLE
Alternative methods for lost connection detection?

### ISSUE THREAD

**Issue by retrofreak83** [TooTallNate/Java-WebSocket#534]
I don't know if the actual behavior is proposed by the RFC. If so: forget my issue :)
If not: Wouldn't it make sense to somehow extend the behavior?
I have the concrete case of a Websocket server which is not able to handle received Websocket pings, but it instead sends pings which the Java-WebSocket implementation correctly answers with pongs.
In my opinion, this, let's call it "reverse heartbeat", would be also a suitable indicator to detect a living connection and thus reset the lost connection timer.

Furthermore, would be the received valid frames would also an option to reset the lost connection timer?

**Comment by marci4** [comment]
Hello @retrofreak83,

the lost connection detection is not specified by the RFC but I use the specified behavior by the RFC for the heartbeat.
This feature takes advantage of the specification in [section 5.5.2](https://tools.ietf.org/html/rfc6455#section-5.5.2) that a endpoint SHOULD respond to a Ping frame with Pong frame as soon as is practical.

As it sounds like your websocket server is not correctly implementing the specification.

Furthermore I think this would not allow a detection of a lost connection since it would require a predefined duration between two pings which both endpoints would have to negotiate. This is not specified by the RFC and so would not be possible with other endpoints.

Theoretically yes, it would be possible but right now I don't feel like implementing a work around for an endpoint which is not implementing the spec correctly.

Apart from this, you can always turn the lost connection detection off!

Greetings
marci4

**Comment by retrofreak83** [comment]
Thanks for your answer.
You are right, according to the RFC and the RFCs meaning of the notion SHOULD, it seems highly reasonable that the other websocket server answers the frameworks pings.

> Apart from this, you can always turn the lost connection detection off!

Yes, for sure, but I thought, extend an existing detection which would work in this case is better than fully go without a check :)

**Comment by marci4** [comment]
Hello @retrofreak83,

can we even solve this issue then?

Since there is no way specified to negotiate a interval, it is not possible for the other endpoint to be sure to send a frame in the right interval. So even if every frame is resetting the timer, there still might be an issue. 

Greetings
marci4

**Comment by retrofreak83** [comment]
I'm fine with closing. At least I could convince the particular developer to implement a "pong" meanwhile ;)
