### ISSUE TITLE
How to stop WebSocketServer when users kill the App rather than normally exit

### ISSUE THREAD

**Issue by richdyang** [TooTallNate/Java-WebSocket#607]
WebSocketServer is not implemented as a Service on Android, so it will keep alive when users kill the App directly.

What should I do to handle this case? There is no lifecycle callback to stop the server.

Application.onTerminate() won't be called.
Activity.onDestroy() won't be called when killing the App.

**Comment by marci4** [comment]
Hello @richdyang,

this lib is not designed for Android only! Due to that reason I cannot implement such methods!

Please implement them and call the respective methods on the websocket server!

Greetings
marci4

**Comment by Tonacatecuhtli** [comment]
Hi @richdyang did you implement this method? because I have the same problem and it would be nice to know how you handled it.

**Comment by actor20170211030627** [comment]
Hi @richdyang I also used in android.I want know what's your proguard rule?  I tried one day yesterday,but faild,Please help me.

**Comment by richdyang** [comment]
@actor20170211030627 you failed what? I don't catch your idea. Is your problem related to this issue? I don't understand for what you configure the proguard. I don't configure proguard rules and I can use WebSocketServer perfectly. Only issue is described in this issue.

**Comment by actor20170211030627** [comment]
Thank You!

**Comment by marci4** [comment]
Hello @richdyang, hello @Tonacatecuhtli ,

I tried it with a simple android app and for me the server was killed automatically.

Could you maybe send me a small test application so I can try to understand the issue a bit more and direct you in the right way. 
Sorry not an android guy, so you need to help me out here!

Greetings
marci4

**Comment by Tonacatecuhtli** [comment]
Hi, so as far as I know, it's like this:
Android gives you some lifecycle methods but for example, there is no guarantee that it calls its onDestroy method. 
@richdyang So what you would have to do ist start/stop the WebSocket server onPause/onResume of your App/[Activity Livecylce](https://developer.android.com/guide/components/activities/activity-lifecycle.html) so that it would be removed from the system if the user kills the app. So this is a bit stupid because you couldn't do large file-transfers or keep the WebSocket connection alive. To keep it alive you would have to write an Android Service for your App. How to handle Services is described here [Processes and Application Lifecycle](https://developer.android.com/guide/components/activities/process-lifecycle.html) 

@marci4  So what I/we would need is the ability to start/stop the server frequently(?) whenever the user pauses the application. I know that's a bit brutal to disconnect everyone when that happens but the App would have to care for that.
And while I'm at it it would be nice if you could actually set the [setReuseAddr](https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/java/org/java_websocket/server/WebSocketServer.java#L197) flag to true but I guess that's also for a reason?

**Comment by marci4** [comment]
Hello @Tonacatecuhtli,

thank you for these information!

So you are just looking for a service implementation and reusing a WebSocketServer?
Why not create a new WebSocketServer? Why is this not possible?

The setReuseAddr flag can be set manually. Check the [wiki](https://github.com/TooTallNate/Java-WebSocket/wiki/Enable-SO_REUSEADDR) for this!

Greetings
marci4

**Comment by Tonacatecuhtli** [comment]
Hi, @marci4 

thanks a lot for the wiki link ;)

I have to say that at this point I wouldn't consider it as an issue for your library anymore. It's more of my responsibility to make it work ;)

But for your questions:
Why not create a new WebSocketServer? Yes, that's what we ended up doing. But then you have to use dynamic ports and implement NSD (Network Service Discovery). At least in our case.

Why is this not possible? It's just not possible if you always use the same port. Especially if you don't know that you cans set the setReuseAddr flag to true xD. 

So you are just looking for a service implementation and reusing a WebSocketServer?  The service implementation is out of the libs scope as well because it would be android specific. Would be nice though ;)

Best regards
Tonacatecuhtli

**Comment by marci4** [comment]
Hello @richdyang,

I will look into the possibility to allow reusing a WebSocketServer, just for you ;

I know, but I feel that many Android developer do not have the passion to implement it on their own and "expect" there to be a solution.

Apart from this, thank you very much for clearing everything up for me!

Greetings
marci4

**Comment by richdyang** [comment]
Thanks all, that's caused by that Application's terminate method cannot be called when app is killed.

So it's not related to WebSocket server. It can be solved by implementing a service by developers.

Please close this issue.
