### ISSUE TITLE
Question: Does onError call onClose?

### ISSUE THREAD

**Issue by forresthopkinsa** [TooTallNate/Java-WebSocket#630]
Hi @marci4 , you might remember me from the StompProtocol library. An issue was raised in my repo concerning websockets closing after `onError` is called. The issue was in the context of using OkHttp, but it brought the question to my attention.

I'm just asking because I haven't seen this clearly documented anywhere and I'd rather get a canonical answer than guess-and-check.

**When the client encounters an error, it calls `onError`. After this, what is the state of the connection? Is it still open? If the error was fatal, does it then go on to call `onClose` *after* that?**

I'm asking this mostly to see how it contrasts with OkHttp's way of doing it.

**Comment by marci4** [comment]
Hello @forresthopkinsa,

the JavaDoc for the WebSocketClient is missing for this I quess.
The onError method for the WebSocketServer is a bit more clear in this case.
`Called when errors occurs. If an error causes the websocket connection to fail onClose(WebSocket, int, String, boolean) will be called additionally.
This method will be called primarily because of IO or protocol errors.
If the given exception is an RuntimeException that probably means that you encountered a bug.`

So yes, onClose should always be called after onError. If you find any case, where that is not the case (apart from errors during the closing process), please report them to me! :)

I have no clue how OkHttp is doing it, sorry!

Greetings
marci4

**Comment by forresthopkinsa** [comment]
Ah, I see. Got it. Thanks!

And yeah, for anyone else wondering, OkHttp combines OnError and OnClose into one method, OnFailure.

**Comment by marci4** [comment]
Hello @forresthopkinsa,

Is this question answered for you? Can I close this issue or do you need more information?

Greetings
marci4

**Comment by forresthopkinsa** [comment]
Oh, no, I'm good. Sorry, I forgot to close. Thanks for the help. 👍
