### ISSUE TITLE
Where the f*ck is there a simple "how to use"?

### ISSUE THREAD

**Issue by mcourteaux** [TooTallNate/Java-WebSocket#644]
For fuck sake.. Why is there no usage example in the main readme. This is a 3500+ stars project on github, without a teaser on how to use this. Bullshit that every java developer knows like how to build, which is an explanation for noobs. We fucking know how you use build systems, etc. We use them all the time. What we are here for is your library! Then freaking show us how to use this thing already. Why the fuck would I have to dive in your sketchy test packages to find an example where you actually instantiate and use this. I mean, my rude words aside, please add an idea of how to use this library. It must be good, as it has 3500 stars, but I am scared because of no demo.

**Comment by mcourteaux** [comment]
I made the effort to add a simple example and opened a pull request. Feel free to merge in.

**Comment by marci4** [comment]
Hello @mcourteaux,

I am always open to suggestions for improvement, but these should be formulated constructively.
However, no one has anything from such statements. They create a bad climate, as well as a reduced interest on my part to put more time into this project after a long working day.

A lot of things are clear to me because I've been working with the API for months. I would be very happy if you describe your problems in a new issue constructively.

About your question: You can find an example class on the first page of the wiki.
You can also find all examples [here](https://github.com/TooTallNate/Java-WebSocket/tree/master/src/main/example).

Greetings
marci4

**Comment by mcourteaux** [comment]
Ye, I had a terrible day. Frustrations were stacking up and I lost it here. 😛 Any reason why the proposed PR is not accepted?

**Comment by marci4** [comment]
Hello @mcourteaux,

there are some reasons. 
The smallest issue is, that I will only merch a PR, if there is an open issue (for discussion, keeping track of issues, etc).

The bigger reason for me is, that we do have a lot of examples in the wiki and I would have to maintain this example as well (yes, I try to check every class for each release).
Also this PR was not complete in the way, that there was no example for a WebSocketServer.

Hope this clears up some confusion.

Greetings
marci4
