### ISSUE TITLE
Give the main WebSocketClient thread and AbstractWebSocket Timer a name

### ISSUE THREAD

**Issue by cjgriscom** [TooTallNate/Java-WebSocket#666]
Only the read thread is assigned a name in a `WebSocketClient` instance. The main `Runnable` acquires a default name like "Thread-7". I'm working on an application where I need to identify threads and manage them, and it would be nice to be able to distinguish them purely by name instead of inspecting their stack trace. 

According to `oakkitten` who it pointed out in [this thread](https://github.com/TooTallNate/Java-WebSocket/pull/464), the [`connect()` method](https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/java/org/java_websocket/client/WebSocketClient.java#L265-L270) creates a `writeThread` field which is [overwritten with a new `WebsocketWriteThread`](https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/java/org/java_websocket/client/WebSocketClient.java#L380-L381) when the thread runs. `WebsocketWriteThread` sets the name, but the thread started in the `connect()` method continues to run with the default name.

Additionally `oakkitten` noted that a new `Timer` is [created](https://github.com/TooTallNate/Java-WebSocket/blob/a5ff3b4bb213767c13b24f0d2e6363d4ff874cd4/src/main/java/org/java_websocket/AbstractWebSocket.java#L131) in `AbstractWebSocket` and it also lacks a name.

**Comment by marci4** [comment]
Some threads are not named, e.g. the `Timer` in `AbstractWebSocket`

## Expected Behavior


All threads, server and client, should have a non default name.

## Current Behavior


Some threads, e.g. the timer, still have their default name.

## Possible Solution


Set thread names!

## Steps to Reproduce (for bugs)


1. Start Server/Client
2. Check for the thread names in the debugger

## Context


Information only change

## Your Environment

* Version used: 1.3.7 
* Java version: - 
* Operating System and version: - 
* Endpoint Name and version: - 
* Link to your project: -


## Include
- [X] Tests
- [X] Documentation

**Comment by marci4** [comment]
Thank you very much for creating this issue @cjgriscom.

Should be solved with #667.

Greetings
marci4
