### ISSUE TITLE
如何注册取消不同的事件

### ISSUE THREAD

**Issue by jayronlou** [TooTallNate/Java-WebSocket#710]
您好，我想问一下，链接websocket之后，如何订阅和取消不同的事件呢？多谢

**Comment by PhilipRoman** [comment]
Instead of using "subscriptions" you create a subclass of WebSocketServer or WebSocketClient and define your callbacks by overriding the methods "`onMessage`", "`onOpen`", "`onStart`" and "`onClose`". You can cancel them either by shutting down the whole socket or using your own logic (by toggling a variable, etc.).  If you're still not sure, take a look at the examples.

I hope I understood your issue correctly.

**Comment by marci4** [comment]
Hello @jayronlou, 

is this issue solved for you?

Best regards,
marci4
