### ISSUE TITLE
Can we remove synchronized appending to queue, this will make code run multithreaded

### ISSUE THREAD

**Issue by brijsinghdev** [TooTallNate/Java-WebSocket#726]
WebSocketImpl.java line#:704	

private void write( List<ByteBuffer> bufs ) {
		synchronized(synchronizeWriteObject) {
			for( ByteBuffer b : bufs ) {
				write( b );
			}
		}
	}
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Java version:
* Operating System and version:
* Endpoint Name and version:
* Link to your project:

**Comment by marci4** [comment]
Hello @brijsinghdev,

I added this to insure that multiple frames are correctly send in order.
Otherwise it would be possible that e.g. a splitted binary frame will be send and in between a ping frame would be received by the other endpoint. This could cause problems which then result in a dropped message.

Best regards,
marci4

**Comment by brijsinghdev** [comment]
Thanks marci4 for reply

Got it.
Is that sync object "**synchronizeWriteObject**" required to be static i.e. is one for whole server,  Will work fine if we make it at each connection level  may be a sync  on socket object?

**Comment by marci4** [comment]
Hello @brijsinghdev,

yeah, you are right about this!
Should not be static just final right?

Thanks for taking a look at this!
@PhilipRoman what do you think, am I missing something here?

Best regards,
marci4

**Comment by PhilipRoman** [comment]
Yeah, no static resources are accessed within the synchronized block so it should be fine!
