### ISSUE TITLE
How to send an ArrayBuffer

### ISSUE THREAD

**Issue by Niall7459** [TooTallNate/Java-WebSocket#762]
I need to send an ArrayBuffer over socket. 

How can this  be achieved?

Thanks

**Comment by PhilipRoman** [comment]
What is the ArrayBuffer class you're mentioning? Is it `org.simpleframework.util.buffer.ArrayBuffer` from SimpleFramework or do you mean the JavaScript ArrayBuffer? If it is from SimpleFramework, you could ask in their forums about how to get the bytes as a byte array or a ByteBuffer.

**Comment by Niall7459** [comment]
I’m executing an new ArrayBuffer() on the data received in javascript but I’m not sure how to actually send an ArrayBuffer

**Comment by Niall7459** [comment]
Il try using simpleframework

**Comment by PhilipRoman** [comment]
Sorry for delayed reply!

If you are talking about Javascript ArrayBuffer, you certainly don't need SimpleFramework! I mentioned it because it was the first thing that came up about ArrayBuffer in Java. Anyway, I think you should take a look at the [Javascript WebSocket documentation](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket).
 I'm closing this issue because it is not related to this project. 

Best regards.
