### ISSUE TITLE
How to ping client from server after sucessful connection

### ISSUE THREAD

**Issue by ihsanhaikalz** [TooTallNate/Java-WebSocket#763]
Hi there.

I saw your library for websocket and I think it's very straightforward than normal websocket as I am new in this websocket development area. I would like to create an application between client and server where client first connects to the server and once that server and client are connected, server then sends the "ping" request to client in order to get the RTT between server and client. I know it's different than normal ping scenario where client pings server. Unfortunately I don't know where to start and not sure if your websocketserver class has the ping function that I can use. If you could help me to point where should I start that would be really helpful. 

Thanks!

**Comment by marci4** [comment]
Hello @ihsanhaikalz,

you got a lot of questions in there, so I try to answer them one by one.

- The websocket protocol does not care if the endpoint is in the role of a client or a server when it comes to ping/pong frames. Both endpoints are allowed to send a ping and the other endpoint has to respond with a pong. We use this to [detect if a connection is lost](https://github.com/TooTallNate/Java-WebSocket/wiki/Lost-connection-detection) (e.g. dropped cellular network)
- Since every endpoint is allowed to send a ping, it is not defined when a ping is send. E.g. chrome will send a ping to the server in a specific interval. Therefore you may wanna look into another "response" to inform the client about a successful protocol initialization.
- Never the less, yes the WebSocketServer does allow you to send a ping using `sendPing()` of [`WebSocket`](https://static.javadoc.io/org.java-websocket/Java-WebSocket/1.3.9/org/java_websocket/WebSocket.html). You can also send a ping with a specific payload, just take a look at the implementation for that!
- Apart from that you do not really need this confirmation, since on both the client and server onOpen will be called if the connection is established successful. 

Hope this clears up some things!

Best regards,
marci4

**Comment by ihsanhaikalz** [comment]
@marci4 Hi. Thanks very much for the info. 

As for the code I am currently following the SimpleServer and EmptyClient classes mentioned in this library and it works in localhost. Now just the question of how to make the client side to connect to server with public IP address.

My server code is something like this.

```
import java.net.InetSocketAddress;
import java.nio.ByteBuffer;

import org.java_websocket.WebSocket;
import org.java_websocket.handshake.ClientHandshake;
import org.java_websocket.server.WebSocketServer;

public class SimpleServer extends WebSocketServer {

	public SimpleServer(InetSocketAddress address) {
		super(address);
	}

	@Override
	public void onOpen(WebSocket conn, ClientHandshake handshake) {
		conn.send("Welcome to the server!"); //This method sends a message to the new client
		broadcast( "new connection: " + handshake.getResourceDescriptor() ); //This method sends a message to all clients connected
		System.out.println("new connection to " + conn.getRemoteSocketAddress());
		long start = System.currentTimeMillis();
		conn.sendPing();
		long end = System.currentTimeMillis();
		conn.send("time start= " + (end-start)); //This method sends a message to the new client

	}

	@Override
	public void onClose(WebSocket conn, int code, String reason, boolean remote) {
		System.out.println("closed " + conn.getRemoteSocketAddress() + " with exit code " + code + " additional info: " + reason);
	}

	@Override
	public void onMessage(WebSocket conn, String message) {
		System.out.println("received message from "	+ conn.getRemoteSocketAddress() + ": " + message);
	}

	@Override
	public void onMessage( WebSocket conn, ByteBuffer message ) {
		System.out.println("received ByteBuffer from "	+ conn.getRemoteSocketAddress());
	}

	@Override
	public void onError(WebSocket conn, Exception ex) {
		System.err.println("an error occured on connection " + conn.getRemoteSocketAddress()  + ":" + ex);
	}
	
	@Override
	public void onStart() {
		System.out.println("server started successfully");
	}
	
	public static void main(String[] args) {
		String host = "localhost";
		int port = 8887;

		WebSocketServer server = new SimpleServer(new InetSocketAddress(host, port));
		server.run();
		
	}
}
```

The server code will ping the client once the connection is established, is that correct? 
As for the client code:

```
import java.net.URI;
import java.net.URISyntaxException;
import java.nio.ByteBuffer;

import org.java_websocket.client.WebSocketClient;
import org.java_websocket.drafts.Draft;
import org.java_websocket.drafts.Draft_6455;
import org.java_websocket.handshake.ServerHandshake;

public class EmptyClient extends WebSocketClient {

	public EmptyClient(URI serverUri, Draft draft) {
		super(serverUri, draft);
	}

	public EmptyClient(URI serverURI) {
		super(serverURI);
	}

	@Override
	public void onOpen(ServerHandshake handshakedata) {
		send("Hello, it is me. Mario :)");
		System.out.println("new connection opened");
	}

	@Override
	public void onClose(int code, String reason, boolean remote) {
		System.out.println("closed with exit code " + code + " additional info: " + reason);
	}

	@Override
	public void onMessage(String message) {
		System.out.println("received message: " + message);
	}

	@Override
	public void onMessage(ByteBuffer message) {
		System.out.println("received ByteBuffer");
	}

	@Override
	public void onError(Exception ex) {
		System.err.println("an error occurred:" + ex);
	}

	public static void main(String[] args) throws URISyntaxException {		
		WebSocketClient client = new EmptyClient(new URI("ws://publicipaddress:8887"));
		client.connect();
	}
}
```

but the client could not connect to the server with its public IP address and the same port opened in the localhost with assumption that the localhost's port is the same as the public IP address' port. This return the error closed with exit code -1 additional info: Connection refused: connect
an error occurred:java.net.ConnectException: Connection refused: connect.

Do you know what is the problem?

**Comment by marci4** [comment]
Hello @ihsanhaikalz,

if I understand you correctly you wanna have the delay between server and client, right?

In regards of the output, yes you will not receive a ping when listening to onMessage(String/ByteBuffer). For using a ping, use `onWebsocketPing`.


You may wanna check out [this](https://gist.github.com/marci4/a4b35949264ea3f59e37fba5c014420c) gist, since I think this will help you!

Best regards,
marci4

**Comment by ihsanhaikalz** [comment]
Hi @marci4. 

Thanks for the code! I have updated my code and now the ping works. 

But the result between normal ping from client to server using ping command line or psping application (20ms) is much better than the ping using websocket from server to client (100ms). I suspect the problem is when pinging with websocket it actually goes to layer 7 application that will take more time instead of only layer 3 TCP/UDP. 

Do you know any other method how to improve the ping result from websocket?

**Comment by marci4** [comment]
Hello @ihsanhaikalz,

for a real representative ping, you need to send the message back to the server, since clocks will be different on different computers.

Apart from this, you can always enable [TCP_NODELAY](https://github.com/TooTallNate/Java-WebSocket/wiki/Enable-TCP_NODELAY). 

Best regards,
marci4

**Comment by marci4** [comment]
Hello @ihsanhaikalz,

is this issue solved for you?

Best regards,
marci4

**Comment by marci4** [comment]
Dead issue!

Closing it.
Best regards,
marci4
