### ISSUE TITLE
Does it support ws://example.com/abc

### ISSUE THREAD

**Issue by XxLittleCxX** [TooTallNate/Java-WebSocket#803]
Hello. I can create my websocket server on root directory (```ws://example.com```)
Can I create it on sub directory? Such as ```ws://example.com/abc```
Thanks

**Comment by marci4** [comment]
Hello @XxLittleCxX,

you cannot create two separat websocket servers, since they bind to one port.
You can however check the provided descriptor during the handshake and reject the connection or save the info for later evaluation.

On how to do it, you can take a look at https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/ServerRejectHandshakeExample.java#L51 overwriting `onWebsocketHandshakeReceivedAsServer`.

Best regards,
marci4

**Comment by PhilipRoman** [comment]
Is this issue solved for you?

**Comment by marci4** [comment]
Dead issue.

Closing it .

Best regards,
Marcel
