### ISSUE TITLE
Close WebSocket Client Connection

### ISSUE THREAD

**Issue by latinosamuel** [TooTallNate/Java-WebSocket#863]
Hello,

I'm developing an application on Android (Java) and I'm having a problem closing a client-side connection (WebSocketClient).

**Description**: Whenever I close a client WebSocket connection, no information is reported to the Server, that the connection was closed to the Client.

I to close the connection on the Client side I am doing the following:

WebSocketClient code where I close the connection:

`mClient.close(1006);
`

On the server side, no client connection log is reported.

Should not I always go through the onClose of the Server when a client connection is closed?

OnClose code on server side:

```
@Override
public void onClose (WebSocket conn, int code, String reason, boolean remote) {
System.out.println ("closed" + conn.getRemoteSocketAddress () + "with exit code" + code + "additional info:" + reason);
}
```

I'm using the following library version (1.3.9):
` "org.java-websocket:Java-WebSocket:1.3.9"`

Can someone help me?
Thank you.

**Comment by PhilipRoman** [comment]
The problem is caused by you using a reserved close code 1006 ("Abnormal Closure"). The connection will actually be closed, but only after the timeout interval (default 60 seconds).

You should use another close code depending on your reason for closing, for example: 1008 ("Policy Violation") or 1011 ("Internal Error").

Also, it's a good idea to use the constants defined in `org.java_websocket.framing.CloseFrame` instead of simple integer values.

**Comment by latinosamuel** [comment]
Hello @PhilipRoman ,

Thanks for the solution. I solved the problem.

**Solution:**
**First:**  I updated the JavaWebSocket library in order to detect the closing bug of the Websocket Client ([# 827](https://github.com/TooTallNate/Java-WebSocket/issues/827)) for version **1.4.0**:

`"org.java-websocket:Java-WebSocket:1.4.0"`

**Finally:**  I used the Close Frame in order to use the predefined constants.
WebSocket Client side lock code (**Code 1011: Internal Error**):

`mClient.close (CloseFrame.UNEXPECTED_CONDITION);`

Thank you.
I'll close the Issue.
