### ISSUE TITLE
I'm getting 3 connections from a client with different ports

### ISSUE THREAD

**Issue by iamchathu** [TooTallNate/Java-WebSocket#867]
**Describe what you would like to know or do**
I'm running Java WebSocket server and using https://github.com/pladaria/reconnecting-websocket as React-Native WebSocket Client. But when started server initially it get 3 connections from same IP with 3 different ports.

**Describe the solution you'd considered**
Is there way only to keep recent port if from same IP rather than 3 connections from same IP?

**Additional context**
Java Swing Application as server and React-Native Android client.

**Comment by haruntuncay** [comment]
AFAIK, it is possible with a simple change. WebSocketServer class holds a Collection of connections, which is a HashSet by default. Since HashSet doesn't allow duplicates, you can solve your problem by overriding both equals method and the hashCode method in WebSocketImpl.java file. 

You can get the InetSocketAddress object of a WebSocket object by calling getRemoteAddress on it.
So, in the equals method, you have to compare if these two WebSocket objects have the same hostname.

And your hashCode method should return a value based on the hostname value of InetSocketAddress.

**Comment by marci4** [comment]
Is this issue solved for you?

Best regards,
Marcel

**Comment by marci4** [comment]
Closing this question as answered.

Best regards,
Marcel
