### ISSUE TITLE
Many types of clients and the same websocket server?

### ISSUE THREAD

**Issue by jaimegarzon** [TooTallNate/Java-WebSocket#875]
I have many types of clients (standar socket, websocket ws, websocket wss). How is it possible that everyone connects to the same websocket server and they are in the same list of connections in common?

**Comment by haruntuncay** [comment]
You can actually connect to same websocket server with each of these, WebSocketClient is just a wrapper around a standart java Socket. However, a standart Socket will not be useful if you don't follow the [websocket protocol](https://tools.ietf.org/html/rfc6455). And with a standart socket, if you send anything that violates the protocol, the connection will be closed immediately. So it just doesn't make sense to use a standart socket.

That is what WebSocketClient is for, it knows the protocol and knows what to send to a WebSocketServer so that it can establish a connection and not get rejected.

**Comment by marci4** [comment]
Hello @jaimegarzon,
is this question answered for you?

Best regards,
Marcel

**Comment by marci4** [comment]
Closing dead issue!

Best regards,
Marcel
