### ISSUE TITLE
Can it be reconnected automatically?

### ISSUE THREAD

**Issue by kigkrazy** [TooTallNate/Java-WebSocket#897]
**Is your feature request related to a problem? Please describe.**
Many people need this feature!!! I can see many issues, so do you consider add it?

**Describe the solution you'd like**
there is a sulotion, you can see it.  
[EasyWs](https://github.com/kigkrazy/EasyWs)
maybe it can add into project.

**Describe alternatives you've considered**

**Additional context**
Add any other context or links about the feature request here.

**Comment by marci4** [comment]
Hello @kigkrazy,

for me personally there are simply too many conditions that are bound to a reconnect and therefore in my eyes this simply cannot be covered globally by the library.

For instance:
The client has no internet connection
The client has a bad internet connection and always drops because its pings cannot be sent to the server.
The server restarts for a short time (less than one second).
The server restarts for a longer time (several minutes).
The server goes into maintainance mode (down for several hours).
The connection is not closed normally (protocol error, unsupported data, invalid UTF8 for the server, too large data packet, missing extension, TLS error).

All this and much more depends on your infrastructure, how you want to report these errors/information to the user and how you want to react to them.

Best regards,
Marcel

**Comment by kigkrazy** [comment]
There are many problems that I didn't think about!!!  
 Thank you for your reply.

===================================
I hope my code can help somebody.
